# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.routing_api import RoutingApi


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutingApi()

    def tearDown(self) -> None:
        pass

    def test_create_routing(self) -> None:
        """Test case for create_routing

        """
        pass

    def test_delete_routing(self) -> None:
        """Test case for delete_routing

        """
        pass

    def test_get_routing(self) -> None:
        """Test case for get_routing

        """
        pass

    def test_list_routing(self) -> None:
        """Test case for list_routing

        """
        pass

    def test_update_routing(self) -> None:
        """Test case for update_routing

        """
        pass


if __name__ == '__main__':
    unittest.main()
