# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_ips_api import SettingIpsApi


class TestSettingIpsApi(unittest.TestCase):
    """SettingIpsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingIpsApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_ips(self) -> None:
        """Test case for get_setting_ips

        """
        pass

    def test_update_setting_ips(self) -> None:
        """Test case for update_setting_ips

        """
        pass


if __name__ == '__main__':
    unittest.main()
