# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.hotspot2_conf_qos_map_exceptions import Hotspot2ConfQOSMapExceptions

class TestHotspot2ConfQOSMapExceptions(unittest.TestCase):
    """Hotspot2ConfQOSMapExceptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfQOSMapExceptions:
        """Test Hotspot2ConfQOSMapExceptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfQOSMapExceptions`
        """
        model = Hotspot2ConfQOSMapExceptions()
        if include_optional:
            return Hotspot2ConfQOSMapExceptions(
                dcsp = 56,
                up = 56
            )
        else:
            return Hotspot2ConfQOSMapExceptions(
        )
        """

    def testHotspot2ConfQOSMapExceptions(self):
        """Test Hotspot2ConfQOSMapExceptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
