# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_super_mail_response import SettingSuperMailResponse

class TestSettingSuperMailResponse(unittest.TestCase):
    """SettingSuperMailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSuperMailResponse:
        """Test SettingSuperMailResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSuperMailResponse`
        """
        model = SettingSuperMailResponse()
        if include_optional:
            return SettingSuperMailResponse(
                data = [
                    unifi_client.models.setting_super_mail.SettingSuperMail(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        key = '', 
                        provider = '', 
                        site_id = '', )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingSuperMailResponse(
        )
        """

    def testSettingSuperMailResponse(self):
        """Test SettingSuperMailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
