# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dpi_group_api import DpiGroupApi


class TestDpiGroupApi(unittest.TestCase):
    """DpiGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DpiGroupApi()

    def tearDown(self) -> None:
        pass

    def test_create_dpi_group(self) -> None:
        """Test case for create_dpi_group

        """
        pass

    def test_delete_dpi_group(self) -> None:
        """Test case for delete_dpi_group

        """
        pass

    def test_get_dpi_group(self) -> None:
        """Test case for get_dpi_group

        """
        pass

    def test_list_dpi_group(self) -> None:
        """Test case for list_dpi_group

        """
        pass

    def test_update_dpi_group(self) -> None:
        """Test case for update_dpi_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
