# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.channel_plan_ap_blacklisted_channels import ChannelPlanApBlacklistedChannels

class TestChannelPlanApBlacklistedChannels(unittest.TestCase):
    """ChannelPlanApBlacklistedChannels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelPlanApBlacklistedChannels:
        """Test ChannelPlanApBlacklistedChannels
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelPlanApBlacklistedChannels`
        """
        model = ChannelPlanApBlacklistedChannels()
        if include_optional:
            return ChannelPlanApBlacklistedChannels(
                channel = 56,
                mac = '',
                timestamp = 56
            )
        else:
            return ChannelPlanApBlacklistedChannels(
        )
        """

    def testChannelPlanApBlacklistedChannels(self):
        """Test ChannelPlanApBlacklistedChannels"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
