# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.heat_map_update_request import HeatMapUpdateRequest

class TestHeatMapUpdateRequest(unittest.TestCase):
    """HeatMapUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HeatMapUpdateRequest:
        """Test HeatMapUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HeatMapUpdateRequest`
        """
        model = HeatMapUpdateRequest()
        if include_optional:
            return HeatMapUpdateRequest(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                description = '',
                map_id = '',
                name = '',
                site_id = '',
                type = ''
            )
        else:
            return HeatMapUpdateRequest(
        )
        """

    def testHeatMapUpdateRequest(self):
        """Test HeatMapUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
