# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.account_update_request import AccountUpdateRequest

class TestAccountUpdateRequest(unittest.TestCase):
    """AccountUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountUpdateRequest:
        """Test AccountUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountUpdateRequest`
        """
        model = AccountUpdateRequest()
        if include_optional:
            return AccountUpdateRequest(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                ip = '',
                name = '',
                networkconf_id = '',
                site_id = '',
                tunnel_config_type = '',
                tunnel_medium_type = 56,
                tunnel_type = 56,
                vlan = 56,
                x_password = ''
            )
        else:
            return AccountUpdateRequest(
        )
        """

    def testAccountUpdateRequest(self):
        """Test AccountUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
