# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_country_api import SettingCountryApi


class TestSettingCountryApi(unittest.TestCase):
    """SettingCountryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingCountryApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_country(self) -> None:
        """Test case for get_setting_country

        """
        pass

    def test_update_setting_country(self) -> None:
        """Test case for update_setting_country

        """
        pass


if __name__ == '__main__':
    unittest.main()
