# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.hotspot2_conf_capab import Hotspot2ConfCapab

class TestHotspot2ConfCapab(unittest.TestCase):
    """Hotspot2ConfCapab unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfCapab:
        """Test Hotspot2ConfCapab
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfCapab`
        """
        model = Hotspot2ConfCapab()
        if include_optional:
            return Hotspot2ConfCapab(
                port = 56,
                protocol = '',
                status = ''
            )
        else:
            return Hotspot2ConfCapab(
        )
        """

    def testHotspot2ConfCapab(self):
        """Test Hotspot2ConfCapab"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
