# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_lcm import SettingLcm

class TestSettingLcm(unittest.TestCase):
    """SettingLcm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingLcm:
        """Test SettingLcm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingLcm`
        """
        model = SettingLcm()
        if include_optional:
            return SettingLcm(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                brightness = 56,
                enabled = True,
                idle_timeout = 56,
                key = '',
                site_id = '',
                sync = True,
                touch_event = True
            )
        else:
            return SettingLcm(
        )
        """

    def testSettingLcm(self):
        """Test SettingLcm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
