# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.hotspot2_conf_cellular_network_list import Hotspot2ConfCellularNetworkList

class TestHotspot2ConfCellularNetworkList(unittest.TestCase):
    """Hotspot2ConfCellularNetworkList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfCellularNetworkList:
        """Test Hotspot2ConfCellularNetworkList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfCellularNetworkList`
        """
        model = Hotspot2ConfCellularNetworkList()
        if include_optional:
            return Hotspot2ConfCellularNetworkList(
                mcc = 56,
                mnc = 56,
                name = ''
            )
        else:
            return Hotspot2ConfCellularNetworkList(
        )
        """

    def testHotspot2ConfCellularNetworkList(self):
        """Test Hotspot2ConfCellularNetworkList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
