# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_porta_response import SettingPortaResponse

class TestSettingPortaResponse(unittest.TestCase):
    """SettingPortaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingPortaResponse:
        """Test SettingPortaResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingPortaResponse`
        """
        model = SettingPortaResponse()
        if include_optional:
            return SettingPortaResponse(
                data = [
                    unifi_client.models.setting_porta.SettingPorta(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        key = '', 
                        site_id = '', 
                        ugw3_wan2_enabled = True, )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingPortaResponse(
        )
        """

    def testSettingPortaResponse(self):
        """Test SettingPortaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
