# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.device_api import DeviceApi


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()

    def tearDown(self) -> None:
        pass

    def test_create_device(self) -> None:
        """Test case for create_device

        """
        pass

    def test_delete_device(self) -> None:
        """Test case for delete_device

        """
        pass

    def test_get_device(self) -> None:
        """Test case for get_device

        """
        pass

    def test_list_device(self) -> None:
        """Test case for list_device

        """
        pass

    def test_update_device(self) -> None:
        """Test case for update_device

        """
        pass


if __name__ == '__main__':
    unittest.main()
