# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.setting_magic_site_to_site_vpn_api import SettingMagicSiteToSiteVpnApi


class TestSettingMagicSiteToSiteVpnApi(unittest.TestCase):
    """SettingMagicSiteToSiteVpnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingMagicSiteToSiteVpnApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_magic_site_to_site_vpn(self) -> None:
        """Test case for get_setting_magic_site_to_site_vpn

        """
        pass

    def test_update_setting_magic_site_to_site_vpn(self) -> None:
        """Test case for update_setting_magic_site_to_site_vpn

        """
        pass


if __name__ == '__main__':
    unittest.main()
