# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.schedule_task_api import ScheduleTaskApi


class TestScheduleTaskApi(unittest.TestCase):
    """ScheduleTaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduleTaskApi()

    def tearDown(self) -> None:
        pass

    def test_create_schedule_task(self) -> None:
        """Test case for create_schedule_task

        """
        pass

    def test_delete_schedule_task(self) -> None:
        """Test case for delete_schedule_task

        """
        pass

    def test_get_schedule_task(self) -> None:
        """Test case for get_schedule_task

        """
        pass

    def test_list_schedule_task(self) -> None:
        """Test case for list_schedule_task

        """
        pass

    def test_update_schedule_task(self) -> None:
        """Test case for update_schedule_task

        """
        pass


if __name__ == '__main__':
    unittest.main()
