# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.setting_usw_api import SettingUswApi


class TestSettingUswApi(unittest.TestCase):
    """SettingUswApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingUswApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_usw(self) -> None:
        """Test case for get_setting_usw

        """
        pass

    def test_update_setting_usw(self) -> None:
        """Test case for update_setting_usw

        """
        pass


if __name__ == '__main__':
    unittest.main()
