# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_usg_api import SettingUsgApi


class TestSettingUsgApi(unittest.TestCase):
    """SettingUsgApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingUsgApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_usg(self) -> None:
        """Test case for get_setting_usg

        """
        pass

    def test_update_setting_usg(self) -> None:
        """Test case for update_setting_usg

        """
        pass


if __name__ == '__main__':
    unittest.main()
