# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.virtual_device_update_request import VirtualDeviceUpdateRequest

class TestVirtualDeviceUpdateRequest(unittest.TestCase):
    """VirtualDeviceUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VirtualDeviceUpdateRequest:
        """Test VirtualDeviceUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VirtualDeviceUpdateRequest`
        """
        model = VirtualDeviceUpdateRequest()
        if include_optional:
            return VirtualDeviceUpdateRequest(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                height_in_meters = 1.337,
                locked = True,
                map_id = '',
                site_id = '',
                type = '',
                x = '',
                y = ''
            )
        else:
            return VirtualDeviceUpdateRequest(
        )
        """

    def testVirtualDeviceUpdateRequest(self):
        """Test VirtualDeviceUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
