# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.tag_api import TagApi


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagApi()

    def tearDown(self) -> None:
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        """
        pass

    def test_list_tag(self) -> None:
        """Test case for list_tag

        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        """
        pass


if __name__ == '__main__':
    unittest.main()
