# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_snmp import SettingSnmp

class TestSettingSnmp(unittest.TestCase):
    """SettingSnmp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSnmp:
        """Test SettingSnmp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSnmp`
        """
        model = SettingSnmp()
        if include_optional:
            return SettingSnmp(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                community = '',
                enabled = True,
                enabled_v3 = True,
                key = '',
                site_id = '',
                username = '',
                x_password = ''
            )
        else:
            return SettingSnmp(
        )
        """

    def testSettingSnmp(self):
        """Test SettingSnmp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
