# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_global_ap_response import SettingGlobalApResponse

class TestSettingGlobalApResponse(unittest.TestCase):
    """SettingGlobalApResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingGlobalApResponse:
        """Test SettingGlobalApResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingGlobalApResponse`
        """
        model = SettingGlobalApResponse()
        if include_optional:
            return SettingGlobalApResponse(
                data = [
                    unifi_client.models.setting_global_ap.SettingGlobalAp(
                        _id = '', 
                        6e_channel_size = 56, 
                        6e_tx_power = 56, 
                        6e_tx_power_mode = '', 
                        ap_exclusions = [
                            ''
                            ], 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        key = '', 
                        na_channel_size = 56, 
                        na_tx_power = 56, 
                        na_tx_power_mode = '', 
                        ng_channel_size = 56, 
                        ng_tx_power = 56, 
                        ng_tx_power_mode = '', 
                        site_id = '', )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingGlobalApResponse(
        )
        """

    def testSettingGlobalApResponse(self):
        """Test SettingGlobalApResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
