# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_ntp_api import SettingNtpApi


class TestSettingNtpApi(unittest.TestCase):
    """SettingNtpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingNtpApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_ntp(self) -> None:
        """Test case for get_setting_ntp

        """
        pass

    def test_update_setting_ntp(self) -> None:
        """Test case for update_setting_ntp

        """
        pass


if __name__ == '__main__':
    unittest.main()
