# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_super_cloudaccess import SettingSuperCloudaccess

class TestSettingSuperCloudaccess(unittest.TestCase):
    """SettingSuperCloudaccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSuperCloudaccess:
        """Test SettingSuperCloudaccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSuperCloudaccess`
        """
        model = SettingSuperCloudaccess()
        if include_optional:
            return SettingSuperCloudaccess(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                device_auth = '',
                device_id = '',
                enabled = True,
                key = '',
                site_id = '',
                ubic_uuid = '',
                x_certificate_arn = '',
                x_certificate_pem = '',
                x_private_key = ''
            )
        else:
            return SettingSuperCloudaccess(
        )
        """

    def testSettingSuperCloudaccess(self):
        """Test SettingSuperCloudaccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
