# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_rsyslogd import SettingRsyslogd

class TestSettingRsyslogd(unittest.TestCase):
    """SettingRsyslogd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingRsyslogd:
        """Test SettingRsyslogd
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingRsyslogd`
        """
        model = SettingRsyslogd()
        if include_optional:
            return SettingRsyslogd(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                debug = True,
                enabled = True,
                ip = '',
                key = '',
                netconsole_enabled = True,
                netconsole_host = '',
                netconsole_port = 56,
                port = 56,
                site_id = '',
                this_controller = True,
                this_controller_encrypted_only = True
            )
        else:
            return SettingRsyslogd(
        )
        """

    def testSettingRsyslogd(self):
        """Test SettingRsyslogd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
