# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.channel_plan_api import ChannelPlanApi


class TestChannelPlanApi(unittest.TestCase):
    """ChannelPlanApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelPlanApi()

    def tearDown(self) -> None:
        pass

    def test_create_channel_plan(self) -> None:
        """Test case for create_channel_plan

        """
        pass

    def test_delete_channel_plan(self) -> None:
        """Test case for delete_channel_plan

        """
        pass

    def test_get_channel_plan(self) -> None:
        """Test case for get_channel_plan

        """
        pass

    def test_list_channel_plan(self) -> None:
        """Test case for list_channel_plan

        """
        pass

    def test_update_channel_plan(self) -> None:
        """Test case for update_channel_plan

        """
        pass


if __name__ == '__main__':
    unittest.main()
