# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.hotspot_package_response import HotspotPackageResponse

class TestHotspotPackageResponse(unittest.TestCase):
    """HotspotPackageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HotspotPackageResponse:
        """Test HotspotPackageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HotspotPackageResponse`
        """
        model = HotspotPackageResponse()
        if include_optional:
            return HotspotPackageResponse(
                data = [
                    openapi_client.models.hotspot_package.HotspotPackage(
                        _id = '', 
                        amount = 1.337, 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        charged_as = '', 
                        currency = '', 
                        custom_payment_fields_enabled = True, 
                        hours = 56, 
                        index = 56, 
                        limit_down = 56, 
                        limit_overwrite = True, 
                        limit_quota = 56, 
                        limit_up = 56, 
                        name = '', 
                        payment_fields_address_enabled = True, 
                        payment_fields_address_required = True, 
                        payment_fields_city_enabled = True, 
                        payment_fields_city_required = True, 
                        payment_fields_country_enabled = True, 
                        payment_fields_country_required = True, 
                        payment_fields_email_enabled = True, 
                        payment_fields_email_required = True, 
                        payment_fields_first_name_enabled = True, 
                        payment_fields_first_name_required = True, 
                        payment_fields_last_name_enabled = True, 
                        payment_fields_last_name_required = True, 
                        payment_fields_state_enabled = True, 
                        payment_fields_state_required = True, 
                        payment_fields_zip_enabled = True, 
                        payment_fields_zip_required = True, 
                        site_id = '', 
                        trial_duration_minutes = 56, 
                        trial_reset = 1.337, )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return HotspotPackageResponse(
        )
        """

    def testHotspotPackageResponse(self):
        """Test HotspotPackageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
