# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.routing_response import RoutingResponse

class TestRoutingResponse(unittest.TestCase):
    """RoutingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutingResponse:
        """Test RoutingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutingResponse`
        """
        model = RoutingResponse()
        if include_optional:
            return RoutingResponse(
                data = [
                    unifi_client.models.routing.Routing(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        enabled = True, 
                        gateway_device = '', 
                        gateway_type = '', 
                        name = '', 
                        site_id = '', 
                        static_route_distance = 56, 
                        static_route_interface = '', 
                        static_route_network = '', 
                        static_route_nexthop = '', 
                        static_route_type = '', 
                        type = '', )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return RoutingResponse(
        )
        """

    def testRoutingResponse(self):
        """Test RoutingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
