# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.channel_plan_radio_table import ChannelPlanRadioTable

class TestChannelPlanRadioTable(unittest.TestCase):
    """ChannelPlanRadioTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelPlanRadioTable:
        """Test ChannelPlanRadioTable
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelPlanRadioTable`
        """
        model = ChannelPlanRadioTable()
        if include_optional:
            return ChannelPlanRadioTable(
                backup_channel = '',
                channel = '',
                device_mac = '',
                name = '',
                tx_power = '',
                tx_power_mode = '',
                width = 56
            )
        else:
            return ChannelPlanRadioTable(
        )
        """

    def testChannelPlanRadioTable(self):
        """Test ChannelPlanRadioTable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
