# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.radius_profile_auth_servers import RADIUSProfileAuthServers

class TestRADIUSProfileAuthServers(unittest.TestCase):
    """RADIUSProfileAuthServers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RADIUSProfileAuthServers:
        """Test RADIUSProfileAuthServers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RADIUSProfileAuthServers`
        """
        model = RADIUSProfileAuthServers()
        if include_optional:
            return RADIUSProfileAuthServers(
                ip = '',
                port = 56,
                x_secret = ''
            )
        else:
            return RADIUSProfileAuthServers(
        )
        """

    def testRADIUSProfileAuthServers(self):
        """Test RADIUSProfileAuthServers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
