# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_super_sdn_api import SettingSuperSdnApi


class TestSettingSuperSdnApi(unittest.TestCase):
    """SettingSuperSdnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingSuperSdnApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_super_sdn(self) -> None:
        """Test case for get_setting_super_sdn

        """
        pass

    def test_update_setting_super_sdn(self) -> None:
        """Test case for update_setting_super_sdn

        """
        pass


if __name__ == '__main__':
    unittest.main()
