# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_global_ap_api import SettingGlobalApApi


class TestSettingGlobalApApi(unittest.TestCase):
    """SettingGlobalApApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingGlobalApApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_global_ap(self) -> None:
        """Test case for get_setting_global_ap

        """
        pass

    def test_update_setting_global_ap(self) -> None:
        """Test case for update_setting_global_ap

        """
        pass


if __name__ == '__main__':
    unittest.main()
