# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_global_switch import SettingGlobalSwitch

class TestSettingGlobalSwitch(unittest.TestCase):
    """SettingGlobalSwitch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingGlobalSwitch:
        """Test SettingGlobalSwitch
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingGlobalSwitch`
        """
        model = SettingGlobalSwitch()
        if include_optional:
            return SettingGlobalSwitch(
                id = '',
                attr_hidden = True,
                attr_hidden_id = '',
                attr_no_delete = True,
                attr_no_edit = True,
                dhcp_snoop = True,
                dot1x_fallback_networkconf_id = '',
                dot1x_portctrl_enabled = True,
                flowctrl_enabled = True,
                jumboframe_enabled = True,
                key = '',
                radiusprofile_id = '',
                site_id = '',
                stp_version = '',
                switch_exclusions = [
                    ''
                    ]
            )
        else:
            return SettingGlobalSwitch(
        )
        """

    def testSettingGlobalSwitch(self):
        """Test SettingGlobalSwitch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
