# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.spatial_record_api import SpatialRecordApi


class TestSpatialRecordApi(unittest.TestCase):
    """SpatialRecordApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpatialRecordApi()

    def tearDown(self) -> None:
        pass

    def test_create_spatial_record(self) -> None:
        """Test case for create_spatial_record

        """
        pass

    def test_delete_spatial_record(self) -> None:
        """Test case for delete_spatial_record

        """
        pass

    def test_get_spatial_record(self) -> None:
        """Test case for get_spatial_record

        """
        pass

    def test_list_spatial_record(self) -> None:
        """Test case for list_spatial_record

        """
        pass

    def test_update_spatial_record(self) -> None:
        """Test case for update_spatial_record

        """
        pass


if __name__ == '__main__':
    unittest.main()
