# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_ether_lighting_response import SettingEtherLightingResponse

class TestSettingEtherLightingResponse(unittest.TestCase):
    """SettingEtherLightingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingEtherLightingResponse:
        """Test SettingEtherLightingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingEtherLightingResponse`
        """
        model = SettingEtherLightingResponse()
        if include_optional:
            return SettingEtherLightingResponse(
                data = [
                    openapi_client.models.setting_ether_lighting.SettingEtherLighting(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        key = '', 
                        network_overrides = [
                            openapi_client.models.setting_ether_lighting_network_overrides.SettingEtherLightingNetworkOverrides(
                                key = '', 
                                raw_color_hex = '', )
                            ], 
                        site_id = '', 
                        speed_overrides = [
                            openapi_client.models.setting_ether_lighting_speed_overrides.SettingEtherLightingSpeedOverrides(
                                key = '', 
                                raw_color_hex = '', )
                            ], )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingEtherLightingResponse(
        )
        """

    def testSettingEtherLightingResponse(self):
        """Test SettingEtherLightingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
