# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.schedule_task_response import ScheduleTaskResponse

class TestScheduleTaskResponse(unittest.TestCase):
    """ScheduleTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleTaskResponse:
        """Test ScheduleTaskResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleTaskResponse`
        """
        model = ScheduleTaskResponse()
        if include_optional:
            return ScheduleTaskResponse(
                data = [
                    openapi_client.models.schedule_task.ScheduleTask(
                        _id = '', 
                        action = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        cron_expr = '', 
                        execute_only_once = True, 
                        name = '', 
                        site_id = '', 
                        upgrade_targets = [
                            openapi_client.models.schedule_task_upgrade_targets.ScheduleTaskUpgradeTargets(
                                mac = '', )
                            ], )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return ScheduleTaskResponse(
        )
        """

    def testScheduleTaskResponse(self):
        """Test ScheduleTaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
