# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.wlan_api import WLANApi


class TestWLANApi(unittest.TestCase):
    """WLANApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WLANApi()

    def tearDown(self) -> None:
        pass

    def test_create_wlan(self) -> None:
        """Test case for create_wlan

        """
        pass

    def test_delete_wlan(self) -> None:
        """Test case for delete_wlan

        """
        pass

    def test_get_wlan(self) -> None:
        """Test case for get_wlan

        """
        pass

    def test_list_wlan(self) -> None:
        """Test case for list_wlan

        """
        pass

    def test_update_wlan(self) -> None:
        """Test case for update_wlan

        """
        pass


if __name__ == '__main__':
    unittest.main()
