# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.hotspot_op_api import HotspotOpApi


class TestHotspotOpApi(unittest.TestCase):
    """HotspotOpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HotspotOpApi()

    def tearDown(self) -> None:
        pass

    def test_create_hotspot_op(self) -> None:
        """Test case for create_hotspot_op

        """
        pass

    def test_delete_hotspot_op(self) -> None:
        """Test case for delete_hotspot_op

        """
        pass

    def test_get_hotspot_op(self) -> None:
        """Test case for get_hotspot_op

        """
        pass

    def test_list_hotspot_op(self) -> None:
        """Test case for list_hotspot_op

        """
        pass

    def test_update_hotspot_op(self) -> None:
        """Test case for update_hotspot_op

        """
        pass


if __name__ == '__main__':
    unittest.main()
