# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.device_outlet_overrides import DeviceOutletOverrides

class TestDeviceOutletOverrides(unittest.TestCase):
    """DeviceOutletOverrides unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceOutletOverrides:
        """Test DeviceOutletOverrides
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceOutletOverrides`
        """
        model = DeviceOutletOverrides()
        if include_optional:
            return DeviceOutletOverrides(
                cycle_enabled = True,
                index = 56,
                name = '',
                relay_state = True
            )
        else:
            return DeviceOutletOverrides(
        )
        """

    def testDeviceOutletOverrides(self):
        """Test DeviceOutletOverrides"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
