# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.dhcp_option_api import DHCPOptionApi


class TestDHCPOptionApi(unittest.TestCase):
    """DHCPOptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DHCPOptionApi()

    def tearDown(self) -> None:
        pass

    def test_create_dhcp_option(self) -> None:
        """Test case for create_dhcp_option

        """
        pass

    def test_delete_dhcp_option(self) -> None:
        """Test case for delete_dhcp_option

        """
        pass

    def test_get_dhcp_option(self) -> None:
        """Test case for get_dhcp_option

        """
        pass

    def test_list_dhcp_option(self) -> None:
        """Test case for list_dhcp_option

        """
        pass

    def test_update_dhcp_option(self) -> None:
        """Test case for update_dhcp_option

        """
        pass


if __name__ == '__main__':
    unittest.main()
