# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.network_api import NetworkApi


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkApi()

    def tearDown(self) -> None:
        pass

    def test_create_network(self) -> None:
        """Test case for create_network

        """
        pass

    def test_delete_network(self) -> None:
        """Test case for delete_network

        """
        pass

    def test_get_network(self) -> None:
        """Test case for get_network

        """
        pass

    def test_list_network(self) -> None:
        """Test case for list_network

        """
        pass

    def test_update_network(self) -> None:
        """Test case for update_network

        """
        pass


if __name__ == '__main__':
    unittest.main()
