# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.dashboard_api import DashboardApi


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardApi()

    def tearDown(self) -> None:
        pass

    def test_create_dashboard(self) -> None:
        """Test case for create_dashboard

        """
        pass

    def test_delete_dashboard(self) -> None:
        """Test case for delete_dashboard

        """
        pass

    def test_get_dashboard(self) -> None:
        """Test case for get_dashboard

        """
        pass

    def test_list_dashboard(self) -> None:
        """Test case for list_dashboard

        """
        pass

    def test_update_dashboard(self) -> None:
        """Test case for update_dashboard

        """
        pass


if __name__ == '__main__':
    unittest.main()
