# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_super_mgmt_response import SettingSuperMgmtResponse

class TestSettingSuperMgmtResponse(unittest.TestCase):
    """SettingSuperMgmtResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSuperMgmtResponse:
        """Test SettingSuperMgmtResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSuperMgmtResponse`
        """
        model = SettingSuperMgmtResponse()
        if include_optional:
            return SettingSuperMgmtResponse(
                data = [
                    unifi_client.models.setting_super_mgmt.SettingSuperMgmt(
                        _id = '', 
                        analytics_disapproved_for = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        auto_upgrade = True, 
                        autobackup_cron_expr = '', 
                        autobackup_days = 56, 
                        autobackup_enabled = True, 
                        autobackup_gcs_bucket = '', 
                        autobackup_gcs_certificate_path = '', 
                        autobackup_local_path = '', 
                        autobackup_max_files = 56, 
                        autobackup_post_actions = [
                            ''
                            ], 
                        autobackup_s3_access_key = '', 
                        autobackup_s3_access_secret = '', 
                        autobackup_s3_bucket = '', 
                        autobackup_timezone = '', 
                        backup_to_cloud_enabled = True, 
                        contact_info_city = '', 
                        contact_info_company_name = '', 
                        contact_info_country = '', 
                        contact_info_full_name = '', 
                        contact_info_phone_number = '', 
                        contact_info_shipping_address_1 = '', 
                        contact_info_shipping_address_2 = '', 
                        contact_info_state = '', 
                        contact_info_zip = '', 
                        data_retention_setting_preference = '', 
                        data_retention_time_in_hours_for_5minutes_scale = 56, 
                        data_retention_time_in_hours_for_daily_scale = 56, 
                        data_retention_time_in_hours_for_hourly_scale = 56, 
                        data_retention_time_in_hours_for_monthly_scale = 56, 
                        data_retention_time_in_hours_for_others = 56, 
                        default_site_device_auth_password_alert = '', 
                        discoverable = True, 
                        enable_analytics = True, 
                        google_maps_api_key = '', 
                        image_maps_use_google_engine = True, 
                        key = '', 
                        led_enabled = True, 
                        live_chat = '', 
                        live_updates = '', 
                        minimum_usable_hd_space = 56, 
                        minimum_usable_sd_space = 56, 
                        multiple_sites_enabled = True, 
                        override_inform_host = True, 
                        override_inform_host_location = '', 
                        site_id = '', 
                        store_enabled = '', 
                        time_series_per_client_stats_enabled = True, 
                        x_ssh_password = '', 
                        x_ssh_username = '', )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingSuperMgmtResponse(
        )
        """

    def testSettingSuperMgmtResponse(self):
        """Test SettingSuperMgmtResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
