# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.hotspot2_conf_friendly_name import Hotspot2ConfFriendlyName

class TestHotspot2ConfFriendlyName(unittest.TestCase):
    """Hotspot2ConfFriendlyName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfFriendlyName:
        """Test Hotspot2ConfFriendlyName
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfFriendlyName`
        """
        model = Hotspot2ConfFriendlyName()
        if include_optional:
            return Hotspot2ConfFriendlyName(
                language = '',
                text = ''
            )
        else:
            return Hotspot2ConfFriendlyName(
        )
        """

    def testHotspot2ConfFriendlyName(self):
        """Test Hotspot2ConfFriendlyName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
