# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.setting_rsyslogd_api import SettingRsyslogdApi


class TestSettingRsyslogdApi(unittest.TestCase):
    """SettingRsyslogdApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingRsyslogdApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_rsyslogd(self) -> None:
        """Test case for get_setting_rsyslogd

        """
        pass

    def test_update_setting_rsyslogd(self) -> None:
        """Test case for update_setting_rsyslogd

        """
        pass


if __name__ == '__main__':
    unittest.main()
