# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        """
        pass

    def test_list_user(self) -> None:
        """Test case for list_user

        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
