# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.map_api import MapApi


class TestMapApi(unittest.TestCase):
    """MapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MapApi()

    def tearDown(self) -> None:
        pass

    def test_create_map(self) -> None:
        """Test case for create_map

        """
        pass

    def test_delete_map(self) -> None:
        """Test case for delete_map

        """
        pass

    def test_get_map(self) -> None:
        """Test case for get_map

        """
        pass

    def test_list_map(self) -> None:
        """Test case for list_map

        """
        pass

    def test_update_map(self) -> None:
        """Test case for update_map

        """
        pass


if __name__ == '__main__':
    unittest.main()
