# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.virtual_device_api import VirtualDeviceApi


class TestVirtualDeviceApi(unittest.TestCase):
    """VirtualDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VirtualDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_create_virtual_device(self) -> None:
        """Test case for create_virtual_device

        """
        pass

    def test_delete_virtual_device(self) -> None:
        """Test case for delete_virtual_device

        """
        pass

    def test_get_virtual_device(self) -> None:
        """Test case for get_virtual_device

        """
        pass

    def test_list_virtual_device(self) -> None:
        """Test case for list_virtual_device

        """
        pass

    def test_update_virtual_device(self) -> None:
        """Test case for update_virtual_device

        """
        pass


if __name__ == '__main__':
    unittest.main()
