# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.device_rps_override import DeviceRpsOverride

class TestDeviceRpsOverride(unittest.TestCase):
    """DeviceRpsOverride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceRpsOverride:
        """Test DeviceRpsOverride
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceRpsOverride`
        """
        model = DeviceRpsOverride()
        if include_optional:
            return DeviceRpsOverride(
                power_management_mode = '',
                rps_port_table = [
                    unifi_client.models.device_rps_port_table.DeviceRpsPortTable(
                        name = '', 
                        port_idx = 56, 
                        port_mode = '', )
                    ]
            )
        else:
            return DeviceRpsOverride(
        )
        """

    def testDeviceRpsOverride(self):
        """Test DeviceRpsOverride"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
