# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.dynamic_dns_api import DynamicDNSApi


class TestDynamicDNSApi(unittest.TestCase):
    """DynamicDNSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DynamicDNSApi()

    def tearDown(self) -> None:
        pass

    def test_create_dynamic_dns(self) -> None:
        """Test case for create_dynamic_dns

        """
        pass

    def test_delete_dynamic_dns(self) -> None:
        """Test case for delete_dynamic_dns

        """
        pass

    def test_get_dynamic_dns(self) -> None:
        """Test case for get_dynamic_dns

        """
        pass

    def test_list_dynamic_dns(self) -> None:
        """Test case for list_dynamic_dns

        """
        pass

    def test_update_dynamic_dns(self) -> None:
        """Test case for update_dynamic_dns

        """
        pass


if __name__ == '__main__':
    unittest.main()
