# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.wlan_sae_psk import WLANSaePsk

class TestWLANSaePsk(unittest.TestCase):
    """WLANSaePsk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WLANSaePsk:
        """Test WLANSaePsk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WLANSaePsk`
        """
        model = WLANSaePsk()
        if include_optional:
            return WLANSaePsk(
                id = '',
                mac = '',
                psk = '',
                vlan = 56
            )
        else:
            return WLANSaePsk(
        )
        """

    def testWLANSaePsk(self):
        """Test WLANSaePsk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
