# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.broadcast_group_api import BroadcastGroupApi


class TestBroadcastGroupApi(unittest.TestCase):
    """BroadcastGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BroadcastGroupApi()

    def tearDown(self) -> None:
        pass

    def test_create_broadcast_group(self) -> None:
        """Test case for create_broadcast_group

        """
        pass

    def test_delete_broadcast_group(self) -> None:
        """Test case for delete_broadcast_group

        """
        pass

    def test_get_broadcast_group(self) -> None:
        """Test case for get_broadcast_group

        """
        pass

    def test_list_broadcast_group(self) -> None:
        """Test case for list_broadcast_group

        """
        pass

    def test_update_broadcast_group(self) -> None:
        """Test case for update_broadcast_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
