# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_radio_ai_response import SettingRadioAiResponse

class TestSettingRadioAiResponse(unittest.TestCase):
    """SettingRadioAiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingRadioAiResponse:
        """Test SettingRadioAiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingRadioAiResponse`
        """
        model = SettingRadioAiResponse()
        if include_optional:
            return SettingRadioAiResponse(
                data = [
                    openapi_client.models.setting_radio_ai.SettingRadioAi(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        auto_adjust_channels_to_country = True, 
                        channels_na = [
                            56
                            ], 
                        channels_ng = [
                            56
                            ], 
                        cron_expr = '', 
                        default = True, 
                        enabled = True, 
                        exclude_devices = [
                            ''
                            ], 
                        ht_modes_na = [
                            56
                            ], 
                        ht_modes_ng = [
                            56
                            ], 
                        key = '', 
                        optimize = [
                            ''
                            ], 
                        radios = [
                            ''
                            ], 
                        setting_preference = '', 
                        site_id = '', 
                        use_xy = True, )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingRadioAiResponse(
        )
        """

    def testSettingRadioAiResponse(self):
        """Test SettingRadioAiResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
