# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.heat_map_point_api import HeatMapPointApi


class TestHeatMapPointApi(unittest.TestCase):
    """HeatMapPointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HeatMapPointApi()

    def tearDown(self) -> None:
        pass

    def test_create_heat_map_point(self) -> None:
        """Test case for create_heat_map_point

        """
        pass

    def test_delete_heat_map_point(self) -> None:
        """Test case for delete_heat_map_point

        """
        pass

    def test_get_heat_map_point(self) -> None:
        """Test case for get_heat_map_point

        """
        pass

    def test_list_heat_map_point(self) -> None:
        """Test case for list_heat_map_point

        """
        pass

    def test_update_heat_map_point(self) -> None:
        """Test case for update_heat_map_point

        """
        pass


if __name__ == '__main__':
    unittest.main()
