# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_connectivity_response import SettingConnectivityResponse

class TestSettingConnectivityResponse(unittest.TestCase):
    """SettingConnectivityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingConnectivityResponse:
        """Test SettingConnectivityResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingConnectivityResponse`
        """
        model = SettingConnectivityResponse()
        if include_optional:
            return SettingConnectivityResponse(
                data = [
                    openapi_client.models.setting_connectivity.SettingConnectivity(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        enable_isolated_wlan = True, 
                        enabled = True, 
                        key = '', 
                        site_id = '', 
                        uplink_host = '', 
                        uplink_type = '', 
                        x_mesh_essid = '', 
                        x_mesh_psk = '', )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingConnectivityResponse(
        )
        """

    def testSettingConnectivityResponse(self):
        """Test SettingConnectivityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
