# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_element_adopt_api import SettingElementAdoptApi


class TestSettingElementAdoptApi(unittest.TestCase):
    """SettingElementAdoptApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingElementAdoptApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_element_adopt(self) -> None:
        """Test case for get_setting_element_adopt

        """
        pass

    def test_update_setting_element_adopt(self) -> None:
        """Test case for update_setting_element_adopt

        """
        pass


if __name__ == '__main__':
    unittest.main()
