# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_super_sdn_response import SettingSuperSdnResponse

class TestSettingSuperSdnResponse(unittest.TestCase):
    """SettingSuperSdnResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSuperSdnResponse:
        """Test SettingSuperSdnResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSuperSdnResponse`
        """
        model = SettingSuperSdnResponse()
        if include_optional:
            return SettingSuperSdnResponse(
                data = [
                    openapi_client.models.setting_super_sdn.SettingSuperSdn(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        auth_token = '', 
                        device_id = '', 
                        enabled = True, 
                        key = '', 
                        migrated = True, 
                        site_id = '', 
                        sso_login_enabled = '', 
                        ubic_uuid = '', )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingSuperSdnResponse(
        )
        """

    def testSettingSuperSdnResponse(self):
        """Test SettingSuperSdnResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
