# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.wlan_group_api import WLANGroupApi


class TestWLANGroupApi(unittest.TestCase):
    """WLANGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WLANGroupApi()

    def tearDown(self) -> None:
        pass

    def test_create_wlan_group(self) -> None:
        """Test case for create_wlan_group

        """
        pass

    def test_delete_wlan_group(self) -> None:
        """Test case for delete_wlan_group

        """
        pass

    def test_get_wlan_group(self) -> None:
        """Test case for get_wlan_group

        """
        pass

    def test_list_wlan_group(self) -> None:
        """Test case for list_wlan_group

        """
        pass

    def test_update_wlan_group(self) -> None:
        """Test case for update_wlan_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
