# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hotspot_package_api import HotspotPackageApi


class TestHotspotPackageApi(unittest.TestCase):
    """HotspotPackageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HotspotPackageApi()

    def tearDown(self) -> None:
        pass

    def test_create_hotspot_package(self) -> None:
        """Test case for create_hotspot_package

        """
        pass

    def test_delete_hotspot_package(self) -> None:
        """Test case for delete_hotspot_package

        """
        pass

    def test_get_hotspot_package(self) -> None:
        """Test case for get_hotspot_package

        """
        pass

    def test_list_hotspot_package(self) -> None:
        """Test case for list_hotspot_package

        """
        pass

    def test_update_hotspot_package(self) -> None:
        """Test case for update_hotspot_package

        """
        pass


if __name__ == '__main__':
    unittest.main()
