# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.hotspot2_conf_api import Hotspot2ConfApi


class TestHotspot2ConfApi(unittest.TestCase):
    """Hotspot2ConfApi unit test stubs"""

    def setUp(self) -> None:
        self.api = Hotspot2ConfApi()

    def tearDown(self) -> None:
        pass

    def test_create_hotspot2_conf(self) -> None:
        """Test case for create_hotspot2_conf

        """
        pass

    def test_delete_hotspot2_conf(self) -> None:
        """Test case for delete_hotspot2_conf

        """
        pass

    def test_get_hotspot2_conf(self) -> None:
        """Test case for get_hotspot2_conf

        """
        pass

    def test_list_hotspot2_conf(self) -> None:
        """Test case for list_hotspot2_conf

        """
        pass

    def test_update_hotspot2_conf(self) -> None:
        """Test case for update_hotspot2_conf

        """
        pass


if __name__ == '__main__':
    unittest.main()
