# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.hotspot2_conf_nai_realm_list import Hotspot2ConfNaiRealmList

class TestHotspot2ConfNaiRealmList(unittest.TestCase):
    """Hotspot2ConfNaiRealmList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfNaiRealmList:
        """Test Hotspot2ConfNaiRealmList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfNaiRealmList`
        """
        model = Hotspot2ConfNaiRealmList()
        if include_optional:
            return Hotspot2ConfNaiRealmList(
                auth_ids = '',
                auth_vals = '',
                eap_method = 56,
                encoding = 56,
                name = '',
                status = True
            )
        else:
            return Hotspot2ConfNaiRealmList(
        )
        """

    def testHotspot2ConfNaiRealmList(self):
        """Test Hotspot2ConfNaiRealmList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
