# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_super_fwupdate_api import SettingSuperFwupdateApi


class TestSettingSuperFwupdateApi(unittest.TestCase):
    """SettingSuperFwupdateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingSuperFwupdateApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_super_fwupdate(self) -> None:
        """Test case for get_setting_super_fwupdate

        """
        pass

    def test_update_setting_super_fwupdate(self) -> None:
        """Test case for update_setting_super_fwupdate

        """
        pass


if __name__ == '__main__':
    unittest.main()
