# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_ips_dns_filters import SettingIpsDNSFilters

class TestSettingIpsDNSFilters(unittest.TestCase):
    """SettingIpsDNSFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingIpsDNSFilters:
        """Test SettingIpsDNSFilters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingIpsDNSFilters`
        """
        model = SettingIpsDNSFilters()
        if include_optional:
            return SettingIpsDNSFilters(
                allowed_sites = [
                    ''
                    ],
                blocked_sites = [
                    ''
                    ],
                blocked_tld = [
                    ''
                    ],
                description = '',
                filter = '',
                name = '',
                network_id = '',
                version = ''
            )
        else:
            return SettingIpsDNSFilters(
        )
        """

    def testSettingIpsDNSFilters(self):
        """Test SettingIpsDNSFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
