# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.port_forward_api import PortForwardApi


class TestPortForwardApi(unittest.TestCase):
    """PortForwardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortForwardApi()

    def tearDown(self) -> None:
        pass

    def test_create_port_forward(self) -> None:
        """Test case for create_port_forward

        """
        pass

    def test_delete_port_forward(self) -> None:
        """Test case for delete_port_forward

        """
        pass

    def test_get_port_forward(self) -> None:
        """Test case for get_port_forward

        """
        pass

    def test_list_port_forward(self) -> None:
        """Test case for list_port_forward

        """
        pass

    def test_update_port_forward(self) -> None:
        """Test case for update_port_forward

        """
        pass


if __name__ == '__main__':
    unittest.main()
