# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.port_profile_api import PortProfileApi


class TestPortProfileApi(unittest.TestCase):
    """PortProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortProfileApi()

    def tearDown(self) -> None:
        pass

    def test_create_port_profile(self) -> None:
        """Test case for create_port_profile

        """
        pass

    def test_delete_port_profile(self) -> None:
        """Test case for delete_port_profile

        """
        pass

    def test_get_port_profile(self) -> None:
        """Test case for get_port_profile

        """
        pass

    def test_list_port_profile(self) -> None:
        """Test case for list_port_profile

        """
        pass

    def test_update_port_profile(self) -> None:
        """Test case for update_port_profile

        """
        pass


if __name__ == '__main__':
    unittest.main()
