# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_create_account(self) -> None:
        """Test case for create_account

        """
        pass

    def test_delete_account(self) -> None:
        """Test case for delete_account

        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        """
        pass

    def test_list_account(self) -> None:
        """Test case for list_account

        """
        pass

    def test_update_account(self) -> None:
        """Test case for update_account

        """
        pass


if __name__ == '__main__':
    unittest.main()
