# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unifi_client.api.dpi_app_api import DpiAppApi


class TestDpiAppApi(unittest.TestCase):
    """DpiAppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DpiAppApi()

    def tearDown(self) -> None:
        pass

    def test_create_dpi_app(self) -> None:
        """Test case for create_dpi_app

        """
        pass

    def test_delete_dpi_app(self) -> None:
        """Test case for delete_dpi_app

        """
        pass

    def test_get_dpi_app(self) -> None:
        """Test case for get_dpi_app

        """
        pass

    def test_list_dpi_app(self) -> None:
        """Test case for list_dpi_app

        """
        pass

    def test_update_dpi_app(self) -> None:
        """Test case for update_dpi_app

        """
        pass


if __name__ == '__main__':
    unittest.main()
