# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.setting_network_optimization_api import SettingNetworkOptimizationApi


class TestSettingNetworkOptimizationApi(unittest.TestCase):
    """SettingNetworkOptimizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingNetworkOptimizationApi()

    def tearDown(self) -> None:
        pass

    def test_get_setting_network_optimization(self) -> None:
        """Test case for get_setting_network_optimization

        """
        pass

    def test_update_setting_network_optimization(self) -> None:
        """Test case for update_setting_network_optimization

        """
        pass


if __name__ == '__main__':
    unittest.main()
