# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.setting_rsyslogd_response import SettingRsyslogdResponse

class TestSettingRsyslogdResponse(unittest.TestCase):
    """SettingRsyslogdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingRsyslogdResponse:
        """Test SettingRsyslogdResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingRsyslogdResponse`
        """
        model = SettingRsyslogdResponse()
        if include_optional:
            return SettingRsyslogdResponse(
                data = [
                    openapi_client.models.setting_rsyslogd.SettingRsyslogd(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        debug = True, 
                        enabled = True, 
                        ip = '', 
                        key = '', 
                        netconsole_enabled = True, 
                        netconsole_host = '', 
                        netconsole_port = 56, 
                        port = 56, 
                        site_id = '', 
                        this_controller = True, 
                        this_controller_encrypted_only = True, )
                    ],
                meta = openapi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingRsyslogdResponse(
        )
        """

    def testSettingRsyslogdResponse(self):
        """Test SettingRsyslogdResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
