# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.setting_super_smtp_response import SettingSuperSmtpResponse

class TestSettingSuperSmtpResponse(unittest.TestCase):
    """SettingSuperSmtpResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingSuperSmtpResponse:
        """Test SettingSuperSmtpResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingSuperSmtpResponse`
        """
        model = SettingSuperSmtpResponse()
        if include_optional:
            return SettingSuperSmtpResponse(
                data = [
                    unifi_client.models.setting_super_smtp.SettingSuperSmtp(
                        _id = '', 
                        attr_hidden = True, 
                        attr_hidden_id = '', 
                        attr_no_delete = True, 
                        attr_no_edit = True, 
                        enabled = True, 
                        host = '', 
                        key = '', 
                        port = 56, 
                        sender = '', 
                        site_id = '', 
                        use_auth = True, 
                        use_sender = True, 
                        use_ssl = True, 
                        username = '', 
                        x_password = '', )
                    ],
                meta = unifi_client.models.meta.Meta(
                    msg = '', 
                    rc = '', )
            )
        else:
            return SettingSuperSmtpResponse(
        )
        """

    def testSettingSuperSmtpResponse(self):
        """Test SettingSuperSmtpResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
