# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from unifi_client.models.wlan_schedule_with_duration import WLANScheduleWithDuration

class TestWLANScheduleWithDuration(unittest.TestCase):
    """WLANScheduleWithDuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WLANScheduleWithDuration:
        """Test WLANScheduleWithDuration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WLANScheduleWithDuration`
        """
        model = WLANScheduleWithDuration()
        if include_optional:
            return WLANScheduleWithDuration(
                duration_minutes = 56,
                name = '',
                start_days_of_week = [
                    ''
                    ],
                start_hour = 56,
                start_minute = 56
            )
        else:
            return WLANScheduleWithDuration(
        )
        """

    def testWLANScheduleWithDuration(self):
        """Test WLANScheduleWithDuration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
