# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.hotspot2_conf_qos_map_dcsp import Hotspot2ConfQOSMapDcsp

class TestHotspot2ConfQOSMapDcsp(unittest.TestCase):
    """Hotspot2ConfQOSMapDcsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotspot2ConfQOSMapDcsp:
        """Test Hotspot2ConfQOSMapDcsp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotspot2ConfQOSMapDcsp`
        """
        model = Hotspot2ConfQOSMapDcsp()
        if include_optional:
            return Hotspot2ConfQOSMapDcsp(
                high = 56,
                low = 56
            )
        else:
            return Hotspot2ConfQOSMapDcsp(
        )
        """

    def testHotspot2ConfQOSMapDcsp(self):
        """Test Hotspot2ConfQOSMapDcsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
