# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from openapi_client.models.device_rps_port_table import DeviceRpsPortTable
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DeviceRpsOverride(BaseModel):
    """
    DeviceRpsOverride
    """ # noqa: E501
    power_management_mode: Optional[StrictStr] = None
    rps_port_table: Optional[List[DeviceRpsPortTable]] = None
    __properties: ClassVar[List[str]] = ["power_management_mode", "rps_port_table"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeviceRpsOverride from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rps_port_table (list)
        _items = []
        if self.rps_port_table:
            for _item in self.rps_port_table:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rps_port_table'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DeviceRpsOverride from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "power_management_mode": obj.get("power_management_mode"),
            "rps_port_table": [DeviceRpsPortTable.from_dict(_item) for _item in obj.get("rps_port_table")] if obj.get("rps_port_table") is not None else None
        })
        return _obj


