# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RoutingUpdateRequest(BaseModel):
    """
    RoutingUpdateRequest
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    attr_hidden: Optional[StrictBool] = None
    attr_hidden_id: Optional[StrictStr] = None
    attr_no_delete: Optional[StrictBool] = None
    attr_no_edit: Optional[StrictBool] = None
    enabled: Optional[StrictBool] = None
    gateway_device: Optional[StrictStr] = None
    gateway_type: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    site_id: Optional[StrictStr] = None
    static_route_distance: Optional[StrictInt] = Field(default=None, alias="static-route_distance")
    static_route_interface: Optional[StrictStr] = Field(default=None, alias="static-route_interface")
    static_route_network: Optional[StrictStr] = Field(default=None, alias="static-route_network")
    static_route_nexthop: Optional[StrictStr] = Field(default=None, alias="static-route_nexthop")
    static_route_type: Optional[StrictStr] = Field(default=None, alias="static-route_type")
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_id", "attr_hidden", "attr_hidden_id", "attr_no_delete", "attr_no_edit", "enabled", "gateway_device", "gateway_type", "name", "site_id", "static-route_distance", "static-route_interface", "static-route_network", "static-route_nexthop", "static-route_type", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RoutingUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RoutingUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "attr_hidden": obj.get("attr_hidden"),
            "attr_hidden_id": obj.get("attr_hidden_id"),
            "attr_no_delete": obj.get("attr_no_delete"),
            "attr_no_edit": obj.get("attr_no_edit"),
            "enabled": obj.get("enabled"),
            "gateway_device": obj.get("gateway_device"),
            "gateway_type": obj.get("gateway_type"),
            "name": obj.get("name"),
            "site_id": obj.get("site_id"),
            "static-route_distance": obj.get("static-route_distance"),
            "static-route_interface": obj.get("static-route_interface"),
            "static-route_network": obj.get("static-route_network"),
            "static-route_nexthop": obj.get("static-route_nexthop"),
            "static-route_type": obj.get("static-route_type"),
            "type": obj.get("type")
        })
        return _obj


