# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SettingSuperMgmt(BaseModel):
    """
    SettingSuperMgmt
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    analytics_disapproved_for: Optional[StrictStr] = None
    attr_hidden: Optional[StrictBool] = None
    attr_hidden_id: Optional[StrictStr] = None
    attr_no_delete: Optional[StrictBool] = None
    attr_no_edit: Optional[StrictBool] = None
    auto_upgrade: Optional[StrictBool] = None
    autobackup_cron_expr: Optional[StrictStr] = None
    autobackup_days: Optional[StrictInt] = None
    autobackup_enabled: Optional[StrictBool] = None
    autobackup_gcs_bucket: Optional[StrictStr] = None
    autobackup_gcs_certificate_path: Optional[StrictStr] = None
    autobackup_local_path: Optional[StrictStr] = None
    autobackup_max_files: Optional[StrictInt] = None
    autobackup_post_actions: Optional[List[StrictStr]] = None
    autobackup_s3_access_key: Optional[StrictStr] = None
    autobackup_s3_access_secret: Optional[StrictStr] = None
    autobackup_s3_bucket: Optional[StrictStr] = None
    autobackup_timezone: Optional[StrictStr] = None
    backup_to_cloud_enabled: Optional[StrictBool] = None
    contact_info_city: Optional[StrictStr] = None
    contact_info_company_name: Optional[StrictStr] = None
    contact_info_country: Optional[StrictStr] = None
    contact_info_full_name: Optional[StrictStr] = None
    contact_info_phone_number: Optional[StrictStr] = None
    contact_info_shipping_address_1: Optional[StrictStr] = None
    contact_info_shipping_address_2: Optional[StrictStr] = None
    contact_info_state: Optional[StrictStr] = None
    contact_info_zip: Optional[StrictStr] = None
    data_retention_setting_preference: Optional[StrictStr] = None
    data_retention_time_in_hours_for_5minutes_scale: Optional[StrictInt] = None
    data_retention_time_in_hours_for_daily_scale: Optional[StrictInt] = None
    data_retention_time_in_hours_for_hourly_scale: Optional[StrictInt] = None
    data_retention_time_in_hours_for_monthly_scale: Optional[StrictInt] = None
    data_retention_time_in_hours_for_others: Optional[StrictInt] = None
    default_site_device_auth_password_alert: Optional[StrictStr] = None
    discoverable: Optional[StrictBool] = None
    enable_analytics: Optional[StrictBool] = None
    google_maps_api_key: Optional[StrictStr] = None
    image_maps_use_google_engine: Optional[StrictBool] = None
    key: Optional[StrictStr] = None
    led_enabled: Optional[StrictBool] = None
    live_chat: Optional[StrictStr] = None
    live_updates: Optional[StrictStr] = None
    minimum_usable_hd_space: Optional[StrictInt] = None
    minimum_usable_sd_space: Optional[StrictInt] = None
    multiple_sites_enabled: Optional[StrictBool] = None
    override_inform_host: Optional[StrictBool] = None
    override_inform_host_location: Optional[StrictStr] = None
    site_id: Optional[StrictStr] = None
    store_enabled: Optional[StrictStr] = None
    time_series_per_client_stats_enabled: Optional[StrictBool] = None
    x_ssh_password: Optional[StrictStr] = None
    x_ssh_username: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_id", "analytics_disapproved_for", "attr_hidden", "attr_hidden_id", "attr_no_delete", "attr_no_edit", "auto_upgrade", "autobackup_cron_expr", "autobackup_days", "autobackup_enabled", "autobackup_gcs_bucket", "autobackup_gcs_certificate_path", "autobackup_local_path", "autobackup_max_files", "autobackup_post_actions", "autobackup_s3_access_key", "autobackup_s3_access_secret", "autobackup_s3_bucket", "autobackup_timezone", "backup_to_cloud_enabled", "contact_info_city", "contact_info_company_name", "contact_info_country", "contact_info_full_name", "contact_info_phone_number", "contact_info_shipping_address_1", "contact_info_shipping_address_2", "contact_info_state", "contact_info_zip", "data_retention_setting_preference", "data_retention_time_in_hours_for_5minutes_scale", "data_retention_time_in_hours_for_daily_scale", "data_retention_time_in_hours_for_hourly_scale", "data_retention_time_in_hours_for_monthly_scale", "data_retention_time_in_hours_for_others", "default_site_device_auth_password_alert", "discoverable", "enable_analytics", "google_maps_api_key", "image_maps_use_google_engine", "key", "led_enabled", "live_chat", "live_updates", "minimum_usable_hd_space", "minimum_usable_sd_space", "multiple_sites_enabled", "override_inform_host", "override_inform_host_location", "site_id", "store_enabled", "time_series_per_client_stats_enabled", "x_ssh_password", "x_ssh_username"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SettingSuperMgmt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SettingSuperMgmt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "analytics_disapproved_for": obj.get("analytics_disapproved_for"),
            "attr_hidden": obj.get("attr_hidden"),
            "attr_hidden_id": obj.get("attr_hidden_id"),
            "attr_no_delete": obj.get("attr_no_delete"),
            "attr_no_edit": obj.get("attr_no_edit"),
            "auto_upgrade": obj.get("auto_upgrade"),
            "autobackup_cron_expr": obj.get("autobackup_cron_expr"),
            "autobackup_days": obj.get("autobackup_days"),
            "autobackup_enabled": obj.get("autobackup_enabled"),
            "autobackup_gcs_bucket": obj.get("autobackup_gcs_bucket"),
            "autobackup_gcs_certificate_path": obj.get("autobackup_gcs_certificate_path"),
            "autobackup_local_path": obj.get("autobackup_local_path"),
            "autobackup_max_files": obj.get("autobackup_max_files"),
            "autobackup_post_actions": obj.get("autobackup_post_actions"),
            "autobackup_s3_access_key": obj.get("autobackup_s3_access_key"),
            "autobackup_s3_access_secret": obj.get("autobackup_s3_access_secret"),
            "autobackup_s3_bucket": obj.get("autobackup_s3_bucket"),
            "autobackup_timezone": obj.get("autobackup_timezone"),
            "backup_to_cloud_enabled": obj.get("backup_to_cloud_enabled"),
            "contact_info_city": obj.get("contact_info_city"),
            "contact_info_company_name": obj.get("contact_info_company_name"),
            "contact_info_country": obj.get("contact_info_country"),
            "contact_info_full_name": obj.get("contact_info_full_name"),
            "contact_info_phone_number": obj.get("contact_info_phone_number"),
            "contact_info_shipping_address_1": obj.get("contact_info_shipping_address_1"),
            "contact_info_shipping_address_2": obj.get("contact_info_shipping_address_2"),
            "contact_info_state": obj.get("contact_info_state"),
            "contact_info_zip": obj.get("contact_info_zip"),
            "data_retention_setting_preference": obj.get("data_retention_setting_preference"),
            "data_retention_time_in_hours_for_5minutes_scale": obj.get("data_retention_time_in_hours_for_5minutes_scale"),
            "data_retention_time_in_hours_for_daily_scale": obj.get("data_retention_time_in_hours_for_daily_scale"),
            "data_retention_time_in_hours_for_hourly_scale": obj.get("data_retention_time_in_hours_for_hourly_scale"),
            "data_retention_time_in_hours_for_monthly_scale": obj.get("data_retention_time_in_hours_for_monthly_scale"),
            "data_retention_time_in_hours_for_others": obj.get("data_retention_time_in_hours_for_others"),
            "default_site_device_auth_password_alert": obj.get("default_site_device_auth_password_alert"),
            "discoverable": obj.get("discoverable"),
            "enable_analytics": obj.get("enable_analytics"),
            "google_maps_api_key": obj.get("google_maps_api_key"),
            "image_maps_use_google_engine": obj.get("image_maps_use_google_engine"),
            "key": obj.get("key"),
            "led_enabled": obj.get("led_enabled"),
            "live_chat": obj.get("live_chat"),
            "live_updates": obj.get("live_updates"),
            "minimum_usable_hd_space": obj.get("minimum_usable_hd_space"),
            "minimum_usable_sd_space": obj.get("minimum_usable_sd_space"),
            "multiple_sites_enabled": obj.get("multiple_sites_enabled"),
            "override_inform_host": obj.get("override_inform_host"),
            "override_inform_host_location": obj.get("override_inform_host_location"),
            "site_id": obj.get("site_id"),
            "store_enabled": obj.get("store_enabled"),
            "time_series_per_client_stats_enabled": obj.get("time_series_per_client_stats_enabled"),
            "x_ssh_password": obj.get("x_ssh_password"),
            "x_ssh_username": obj.get("x_ssh_username")
        })
        return _obj


