# coding: utf-8

"""
    Unifi API

    Unifi Controller API

    The version of the OpenAPI document: 8.0.26
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    attr_hidden: Optional[StrictBool] = None
    attr_hidden_id: Optional[StrictStr] = None
    attr_no_delete: Optional[StrictBool] = None
    attr_no_edit: Optional[StrictBool] = None
    blocked: Optional[StrictBool] = None
    dev_id_override: Optional[StrictInt] = None
    fixed_ap_enabled: Optional[StrictBool] = None
    fixed_ap_mac: Optional[StrictStr] = None
    fixed_ip: Optional[StrictStr] = None
    hostname: Optional[StrictStr] = None
    ip: Optional[StrictStr] = None
    last_seen: Optional[StrictInt] = None
    local_dns_record: Optional[StrictStr] = None
    local_dns_record_enabled: Optional[StrictBool] = None
    mac: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    network_id: Optional[StrictStr] = None
    note: Optional[StrictStr] = None
    site_id: Optional[StrictStr] = None
    use_fixedip: Optional[StrictBool] = None
    usergroup_id: Optional[StrictStr] = None
    virtual_network_override_enabled: Optional[StrictBool] = None
    virtual_network_override_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_id", "attr_hidden", "attr_hidden_id", "attr_no_delete", "attr_no_edit", "blocked", "dev_id_override", "fixed_ap_enabled", "fixed_ap_mac", "fixed_ip", "hostname", "ip", "last_seen", "local_dns_record", "local_dns_record_enabled", "mac", "name", "network_id", "note", "site_id", "use_fixedip", "usergroup_id", "virtual_network_override_enabled", "virtual_network_override_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "attr_hidden": obj.get("attr_hidden"),
            "attr_hidden_id": obj.get("attr_hidden_id"),
            "attr_no_delete": obj.get("attr_no_delete"),
            "attr_no_edit": obj.get("attr_no_edit"),
            "blocked": obj.get("blocked"),
            "dev_id_override": obj.get("dev_id_override"),
            "fixed_ap_enabled": obj.get("fixed_ap_enabled"),
            "fixed_ap_mac": obj.get("fixed_ap_mac"),
            "fixed_ip": obj.get("fixed_ip"),
            "hostname": obj.get("hostname"),
            "ip": obj.get("ip"),
            "last_seen": obj.get("last_seen"),
            "local_dns_record": obj.get("local_dns_record"),
            "local_dns_record_enabled": obj.get("local_dns_record_enabled"),
            "mac": obj.get("mac"),
            "name": obj.get("name"),
            "network_id": obj.get("network_id"),
            "note": obj.get("note"),
            "site_id": obj.get("site_id"),
            "use_fixedip": obj.get("use_fixedip"),
            "usergroup_id": obj.get("usergroup_id"),
            "virtual_network_override_enabled": obj.get("virtual_network_override_enabled"),
            "virtual_network_override_id": obj.get("virtual_network_override_id")
        })
        return _obj


